"""empty message

Revision ID: 4807b54b3ade
Revises: 
Create Date: 2017-11-29 02:52:05.579644

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4807b54b3ade'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('works',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=128), nullable=True),
    sa.Column('alias', sa.String(length=128), nullable=True),
    sa.Column('type', sa.String(length=128), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('institute', sa.String(length=128), nullable=True),
    sa.Column('adjusted_count', sa.Float(), nullable=True),
    sa.Column('ee', sa.String(length=128), nullable=True),
    sa.Column('booktitle', sa.String(length=128), nullable=True),
    sa.Column('real_url', sa.String(length=128), nullable=True),
    sa.Column('keyword', sa.String(length=128), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_works_key'), 'works', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_works_key'), table_name='works')
    op.drop_table('works')
    # ### end Alembic commands ###
